[toolchain]
package_manager = "yarn"
anchor_version = "0.29.0"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
flowbadge= "J4AF7z9dq3GJoZqHDQnVfA1gWqok4uVGgLEZfXnQ3fZ3"
flowlend= "Egw3ax73PVz2BcWejskqUTKKyKyvAWEJS4F2xCnfzgmq"
flowpay= "2ckZpHaho8MjoKtepBE3NvrrtSKDSuSX7xoQ1Y8K6aa4"
flowscore="EpnRYokwwxagwRqRASoK7ndKJBerhzHZnx6uxy7aGUS8"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]


