[toolchain]
anchor_version = "0.29.0"
solana_version = "4.1.0-beta.2"

[features]
seeds = false
skip-lint = false

[programs.devnet]
flowbadge = "GimhF4JiKJfvr2ydNkqcm57zUjGaFy1FSuki1RdLAuL4"
flowlend = "2ftLyg3WpPoLdbRT1Hdy2gYGeizspERPkyR3rKxJA3Kc"
flowpay = "DpcbN1E3mMKBRFgg2t7LL65ThbLAhjMzzfseT6R8dxzL"
flowscore = "BZzGSPdGew1yDkWLfmigabKd6cGkBPRoEaZnAMm8cqAK"

[programs.localnet]
flowbadge = "GimhF4JiKJfvr2ydNkqcm57zUjGaFy1FSuki1RdLAuL4"
flowlend = "2ftLyg3WpPoLdbRT1Hdy2gYGeizspERPkyR3rKxJA3Kc"
flowpay = "DpcbN1E3mMKBRFgg2t7LL65ThbLAhjMzzfseT6R8dxzL"
flowscore = "BZzGSPdGew1yDkWLfmigabKd6cGkBPRoEaZnAMm8cqAK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tyler/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
